name: Broward College   Kenpo Kobudo Martial Arts Club
favicon: null
layout_spectrum: 0.31126
typography_spectrum: 0.43528
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#121317'
    - '#e3dedb'
    - '#693633'
    - '#bdae9b'
    - '#97744e'
  brandStrength: 0.31984717096202075
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
